<div class="index flickr-images">
	<div class="flickr-image">
		<img src="/images/test.jpg" alt="test" />
	</div><div class="flickr-image">
		<img src="/images/test.jpg" alt="test" />
	</div><div class="flickr-image">
		<img src="/images/test.jpg" alt="test" />
	</div><div class="flickr-image">
		<img src="/images/test.jpg" alt="test" />
	</div><div class="flickr-image">
		<img src="/images/test.jpg" alt="test" />
	</div><div class="flickr-image">
		<img src="/images/test.jpg" alt="test" />
	</div><div class="flickr-image">
		<img src="/images/test.jpg" alt="test" />
	</div><div class="flickr-image">
		<img src="/images/test.jpg" alt="test" />
	</div><div class="flickr-image">
		<img src="/images/test.jpg" alt="test" />
	</div><div class="flickr-image">
		<img src="/images/test.jpg" alt="test" />
	</div>
</div>