<html>
	<head>
		<link rel="stylesheet" href="/css/fonts.css" media="screen, projection" />
		<link rel="stylesheet" href="/css/styles.css" media="screen, projection" />
		<script type="text/javascript" href="/js/scripts.js"></script>
		<title>Flickr Images!</title>
	</head>
	<body>
	<div id="container">
		<div id="header">
			<h1>Flickr Images</h1>
		</div>
		<div id="content">
			<?php echo $this->layout()->content; ?>
		</div>
		<div id="footer">
			Seth C. Malaki (c) 2012
		</div>
	</div>		
	</body>
</html>